kubelet:
  enabled: true
  serviceMonitor:
    enabled: true
    https: true
    insecureSkipVerify: true
    interval: 30s

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    ruleSelector: {}
    scrapeInterval: 30s

    alertingEndpoints:
      - name: alertmanager
        namespace: monitoring
        port: web

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi

  service:
    name: "prometheus"
    type: ClusterIP
    port: 9090
  ingress:
    enabled: false

## Node Exporter configuration
nodeExporter:
  enabled: true

  # Service configuration
  service:
    type: ClusterIP
    ports:
      http: 9100

  # Resources
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi

  # Host network and PID namespace
  hostNetwork: true
  hostPID: true

## Kube State Metrics configuration
kubeStateMetrics:
  enabled: true

  # Service configuration
  service:
    type: ClusterIP
    ports:
      http: 8080

  # Resources
  resources:
    limits:
      cpu: 100m
      memory: 190Mi
    requests:
      cpu: 10m
      memory: 32Mi

## Operator configuration
operator:
  enabled: true

  # Service configuration
  service:
    type: ClusterIP
    ports:
      http: 8080

  # Resources
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi

## ServiceMonitor configurations
serviceMonitor:
  enabled: true
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-prometheus

## RBAC
rbac:
  create: true
  pspEnabled: false

## Service Account
serviceAccount:
  create: true
  automountServiceAccountToken: true

## Security Context
podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  runAsNonRoot: true

## Additional scrape configs for custom metrics
additionalScrapeConfigs:
  enabled: false
  configs: []
