controller:
  # Setting the service type, namespace, and other configurations
  serviceType: ClusterIP
  servicePort: 8080
  namespace: jenkins
  #jenkinsUrl: "http://jenkins.local"
  jenkinsHome: /var/jenkins_home

  # Installing additional plugins
  installPlugins:
    - kubernetes:4358.vcfd9c5a_0a_f51
    - git:5.7.0
    - configuration-as-code:1971.vf9280461ea_89
    - workflow-aggregator:608.v67378e9d3db_1
    - locale:587.v7b_843928a_719
    - job-dsl:1.93
  JCasC:
    configScripts:
      hello-world-job: |
        jobs:
          - script: >
              job('hello-world') {
                description('Simple Hello World job')
                steps {
                  shell('echo Hello, World!')
                }
              }

persistence:
  enabled: true
  existingClaim:
  storageClass: jenkins-pv
  accessMode: "ReadWriteOnce"
  size: "2Gi"
